pipeline {
  agent any
  environment {
    DISCORD_WEBHOOK_URL = credentials('DISCORD-WEBHOOK-URL')
  }
  tools {
    maven 'maven 3.9.12'
  }
  stages {
    stage("build") {
      when {
        changeset "**/worker/**"
      }
      steps {
        echo 'Compiling worker app'
        dir('worker') {
          sh 'mvn compile'
        }
      }
    }
    stage("test") {
      when {
        changeset "**/worker/**"
      }
      steps {
        echo 'Running Unit Tests on worker app'
        dir('worker') {
          sh 'mvn clean test'
        }
      }
    }
    stage("package") {
      when {
        branch 'master'
        changeset "**/worker/**"
      }
      steps {
        echo 'Packaging worker app'
        dir('worker') {
          sh 'mvn package -DskipTests'
          archiveArtifacts artifacts: '**/target/*.jar', fingerprint: true
        }
      }
    }
  }
  post {
    always {
      echo 'Building multibranch pipeline for worker is completed..'
      discordSend webhookURL: DISCORD_WEBHOOK_URL,
                  title: "${env.JOB_BASE_NAME} #${env.BUILD_NUMBER}",
                  result: currentBuild.currentResult,
                  description: "**Build:** ${env.BUILD_NUMBER}\n",
                  enableArtifactsList: true,
                  successful: true,
                  showChangeset: true
    }
  }
}