pipeline {
  agent none
  environment {
    DISCORD_WEBHOOK_URL = credentials('DISCORD-WEBHOOK-URL')
  }
  stages {
    stage("build") {
      when {
        changeset "**/worker/**"
      }
      agent {
        docker {
          image 'maven:3.9.12-sapmachine-21'
          args '-v $HOME/.m2:/root/.m2'
        }
      }
      steps {
        echo 'Compiling worker app'
        dir('worker') {
          sh 'mvn compile'
        }
      }
    }
    stage("test") {
      when {
        changeset "**/worker/**"
      }
      agent {
        docker {
          image 'maven:3.9.12-sapmachine-21'
          args '-v $HOME/.m2:/root/.m2'
        }
      }
      steps {
        echo 'Running Unit Tests on worker app'
        dir('worker') {
          sh 'mvn clean test'
        }
      }
    }
    stage("docker-package") {
      agent any
      when {
        branch 'master'
        changeset "**/worker/**"
      }
      steps {
        echo 'Packaging worker app with Docker'
        script {
          docker.withRegistry('https://index.docker.io/v1/', 'docker-vkhash') {
            def workerImage = docker.build("vkhash/private:worker-v${env.BUILD_ID}", "./worker")
            workerImage.push()
            workerImage.push("worker-latest")
          }
        }
      }
    }
  }
  post {
    always {
      echo 'Building multibranch pipeline for worker is completed..'
      discordSend webhookURL: DISCORD_WEBHOOK_URL,
                  title: "${env.JOB_BASE_NAME} #${env.BUILD_NUMBER}",
                  result: currentBuild.currentResult,
                  description: "**App:** worker\n**Build:** ${env.BUILD_NUMBER}\n",
                  enableArtifactsList: false,
                  successful: true,
                  showChangeset: true
    }
  }
}